### ISSUE TITLE
Trigger specific function within downstream repository

### ISSUE THREAD

**Issue by ccwillia** [drone-plugins/drone-downstream#17]
I am able to trigger a downstream repository, but i would like to trigger a specific section in the downstream .drone.yml.   The downstream repo has contains various functional tests and i would like to create sections in my drone file like run-functional-test-a and run-functional-test-b.  Is that possible?

**Comment by tboerger** [comment]
Not possible yet.

**Comment by ccwillia** [comment]
I should be able to utilize the branches feature and store different variations of .drone.yml, but it would sure be awesome to be able to pass parameters downstream.  Even utilizing the drone secrets would be an option if you could create secrets within the drone.yml

**Comment by tboerger** [comment]
This is nothing we will build in the near future
