### ISSUE TITLE
Make PLUGIN_SERVER also variable by DOWNSTREAM_SERVER (like DOWNSTREAM_TOKEN)

### ISSUE THREAD

**Issue by bkleef** [drone-plugins/drone-downstream#18]
I would like to set server by secrets in Drone 0.7. As described [here](http://docs.drone.io/release-0.6.0-secrets#plugins) it recommended to also use the plugin name as ENV prefix like done [here](https://github.com/drone-plugins/drone-docker/blob/5960727df013cf49ed6786fbdf61a99727d78d4b/main.go#L151) in [drone-docker](https://github.com/drone-plugins/drone-docker).

**Comment by tboerger** [comment]
Pull requests are welcome.

**Comment by tboerger** [comment]
Better late than never: https://github.com/drone-plugins/drone-downstream/pull/23
