### ISSUE TITLE
Can't restart running task

### ISSUE THREAD

**Issue by delfer** [drone-plugins/drone-downstream#20]
**Expected**
build restarted
or
new build in poarallel or in queue

**Got**

> Error: unable to trigger build for aaa/bbb.

The same with or w/o `PLUGIN_FORK=true`

`docker run --rm -e PLUGIN_SERVER=https://drone.xxx -e PLUGIN_REPOSITORIES=YYY/zzz -e PLUGIN_TOKEN=mmm -e PLUGIN_FORK=true plugins/downstream`

**Comment by tboerger** [comment]
Are you sure that the token is correct? Never had this issue.

**Comment by delfer** [comment]
Yes, token is correct. I can start not running task and can't restart already running.

**Comment by tboerger** [comment]
I think https://github.com/drone-plugins/drone-downstream/pull/16 would solve this issue.

**Comment by tboerger** [comment]
With https://github.com/drone-plugins/drone-downstream/pull/16#pullrequestreview-62140599 you can wait for finishing the previous builds.
