### ISSUE TITLE
Error info is lost here

### ISSUE THREAD

**Issue by olegabr** [drone-plugins/drone-downstream#22]
https://github.com/drone-plugins/drone-downstream/blob/e6e5010d3459f7d18190ae3735362fbb4fc928d7/plugin.go#L62

The actual error is ignored and the resulting error message in build log is not informative.
The only way to see the actual error is to see in `drone` server logs.

**Comment by tboerger** [comment]
How does your `.drone.yml` look like? This variable is directly set via the content of this file.

**Comment by olegabr** [comment]
The problem was in absence of row in the `config` table for the repository in question. I've found it from `drone` logs. But it is not the question of this issue. The actual question here is that current implementation doesn't show the error reason in the drone UI. The user is forced to see drone logs in order to figure out the actual problem.
Hope it helps.

**Comment by MOZGIII** [comment]
Totally seems like a bug. Why not just fix it?
