### ISSUE TITLE
Ability to trigger a deployment

### ISSUE THREAD

**Issue by MOZGIII** [drone-plugins/drone-downstream#25]
The ability to trigger a deployment is a well suited feature for this project. Can we add it?

**Comment by tboerger** [comment]
But deployments are not triggered automatically so far.

**Comment by MOZGIII** [comment]
Isn't deployment technically the same as just triggering a regular build? With just `event` parameter set to `deployment` and `deploy_to` set to wherever it should deploy?

**Comment by MOZGIII** [comment]
Actually, I'd be good if the plugin would just allow specifying arbitrary parameters. I can adapt it to my needs from that.

**Comment by BenjaminLSmith** [comment]
+1 on this. Having the ability to trigger a 'deployment' event on a downstream repo would be helpful in the cases where I want to trigger a subset of the downstream repo's drone build.

**Comment by tboerger** [comment]
> EDIT2: I ended up just dockerizing drone-cli (it's at https://github.com/MOZGIII/drone-cli-docker if someone's interested).

There is already an official cli docker image at https://hub.docker.com/r/drone/cli/

**Comment by MOZGIII** [comment]
It's buid from scratch, and that doesn't work for me inside of drone (I need `bash`). So I've build my own.

**Comment by jesselang** [comment]
Brad was kind enough to suggest a deployment for my use case of doing downstream validation builds where the desire is to run certain steps and not others. I will be submitting a PR for the option to trigger a deployment. Having thorough reviews of #37, #39, and #40 would be helpful to avoid code conflicts.

**Comment by rohit-smpx** [comment]
Closed in #47?

You can use `deploy` as an option. The value is the environment/target for the deployment. Though it currently doesn't work with branch option (https://github.com/drone-plugins/drone-downstream/issues/59#issuecomment-517131405)
