### ISSUE TITLE
Rebuild docker container for changes 2016-08-23...2017-09-13

### ISSUE THREAD

**Issue by delfer** [drone-plugins/drone-downstream#27]
Hello!
Docker container https://hub.docker.com/r/plugins/downstream/ created "2016-08-23T21:54:06.588712933Z" and should be updated to master branch.

**Comment by tboerger** [comment]
Nope, this container is for drone <= 0.4, since drone >= 0.5 it's https://hub.docker.com/r/plugins/downstream/.

**Comment by tboerger** [comment]
I just have seen that the publishing still needs an update because it's not using the secrets.

**Comment by delfer** [comment]
@tboerger due date?

**Comment by tboerger** [comment]
Will be solved via https://github.com/drone-plugins/drone-downstream/pull/28

**Comment by delfer** [comment]
PR merged, but image on docker hub still old.

**Comment by tboerger** [comment]
True, the webhook failed

**Comment by delfer** [comment]
And when we can pull new version?

**Comment by tboerger** [comment]
Sorry that I have not done that earlier. It's published now.
