### ISSUE TITLE
docker tag management

### ISSUE THREAD

**Issue by ozbillwang** [drone-plugins/drone-downstream#32]
@tboerger 

Could I ask to not override the exist tag when run a new build?

https://github.com/drone-plugins/drone-downstream/blob/master/.drone.yml#L62

     tags: [ latest, 1.0.0, 1.0, 1 ]

I recently got error with this plugins. 

    Error: unable to get latest build for orig/project-1

And I found there is a new docker push 12 days before. 

Could you please add a new tag and push the docker image with build number, such as `1.0.<build_number>`? So we can easily trace the docker image tag, when we have issue with it?

I think the same fix should be deployed to all other plungin as well.

**Comment by ozbillwang** [comment]
![screen shot 2017-10-31 at 1 49 46 pm](https://user-images.githubusercontent.com/8954908/32205500-af150ac8-be43-11e7-982f-ef6a36dfd9ef.png)


It is hard for me to find out which one is the good one I can use. Clearly the latest one with other tag built 12 days are all broken. And the only one left is a 1-year old image. 

This makes my build chains broken.

**Comment by bradrydzewski** [comment]
The proposal I have is to only update `latest` on push to master, and then to create semver docker tags (eg 1, 1.0, 1.0.0, etc) only when git tags are created. This is what we are doing for drone core. I have a proposed update to the docker plugin that I wrote up a while ago that would simplify this. See  https://github.com/drone-plugins/drone-docker/issues/150

**Comment by tboerger** [comment]
Solved via #42, every push to master will generally only write `latest`, with all new features or bug fixes we will tag a version via git tags.
