### ISSUE TITLE
Support for what event to trigger

### ISSUE THREAD

**Issue by JohnRoesler** [drone-plugins/drone-downstream#41]
I don't see in the documentation that you can specify what event type to trigger in the downstream repo. Appears to trigger the most recent drone run , but I am interested in triggering a specific type of run, like a `tag` event. I'd be happy to work on a PR for that

If I'm missing seeing it somewhere, my apologies!

**Comment by jesselang** [comment]
Hey @JohnRoesler, you are correct. There's currently no support for the event type. Looking at https://github.com/drone/drone-go/blob/master/drone/client.go, there isn't an apparent way to trigger a `tag` even. Perhaps you could pass the right combination of parameters such that the server would synthesize it into a `tag` event.

I'd like to add support for deploying to environments, as it would meet some of the needs I'm running into, however, I currently have 3 PRs that have sat dormant for 3+ months with what appears to be a lack of reviews. 😞

Thanks!
