### ISSUE TITLE
Adding an option to poll the status of the downstream build

### ISSUE THREAD

**Issue by nani3105** [drone-plugins/drone-downstream#60]
I am looking to fail the current build if the downstream build fails. Would be good to provide an option like 'watch' which would poll the status of the downstream build.

**Comment by tboerger** [comment]
What about the already existing flag? wait

**Comment by nani3105** [comment]
According to my understanding the flag "wait" will wait for any pending, running downstream build to pass/fail. after which it will kick a new build. But it will not monitor the current build status which was trigger by the plugin

**Comment by zacksinclair** [comment]
+1 for this feature; as far as i can tell, wait doesn't accomplish this.

For our implementation, the value in the downstream build is to run integration tests and know if they pass; currently, have to go dig around in Drone's UI to find the correct build ID to know if it passed or not.

**Comment by bradrydzewski** [comment]
I agree that we should have the option to wait until the build completes. I am closing in favor of https://github.com/drone-plugins/drone-downstream/issues/68 which encapsulates this issue.
