### ISSUE TITLE
Extract `server` setting from environment variables

### ISSUE THREAD

**Issue by simonmeusel** [drone-plugins/drone-downstream#62]
Drone automatically exposes the following environment variables containing the drone server:

```
DRONE_SYSTEM_HOST=drone.exmaple.com
DRONE_SYSTEM_HOSTNAME=drone.exmaple.com
DRONE_BUILD_LINK=https://drone.exmaple.com/repo-owner/repo-name/42
```

I think it would be possible to extract the `server` setting from `DRONE_BUILD_LINK` (because that also includes the protocol and port). Then the `server` setting would be optional.

It would make it easier to configure the `.drone.yml` and would make it more generally applicable and more independent of the particular network setup.

If this is feature is already implemented, please add a note to the docs (http://plugins.drone.io/fr/drone-plugins/drone-downstream/).

**Comment by tboerger** [comment]
Maybe we could add that as a default, but I think we were lacking these vars in previous versions

**Comment by rohit-smpx** [comment]
Protocol is available at `DRONE_SYSTEM_PROTO`
> https://exec-runner.docs.drone.io/configuration/variables/drone-system-proto/

So we can just use `DRONE_SYSTEM_PROTO` and `DRONE_SYSTEM_HOST`

**Comment by tboerger** [comment]
Exec runner won't help. But if agents/docker runner provides the required variables we could default to them

**Comment by rohit-smpx** [comment]
I just posted that reference's link, it's available in all runners I think:
Docker: https://docker-runner.docs.drone.io/configuration/environment/variables/drone-system-proto/
SSH: https://ssh-runner.docs.drone.io/configuration/variables/drone-system-proto/
DO: https://digitalocean-runner.docs.drone.io/configuration/variables/drone-system-proto/
