### ISSUE TITLE
Could you release a new version?

### ISSUE THREAD

**Issue by ryysud** [drone-plugins/drone-downstream#76]
The difference between master and latest version (v1.2.0) is getting bigger: https://github.com/drone-plugins/drone-downstream/compare/v1.2.0...master
We use the downstream plugin as a docker container and want to avoid using the latest tag,
Could you release a new version?

**Comment by alikhil** [comment]
@tboerger

**Comment by tphoney** [comment]
https://hub.docker.com/r/plugins/downstream/tags 1.3.0 was released ! 🍺
